# Generated by Django 3.2.9 on 2021-11-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='last_login',
            field=models.CharField(default='last', max_length=30),
            preserve_default=False,
        ),
    ]
