# Generated by Django 3.2.9 on 2021-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0002_registro_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('mensaje', models.TextField(max_length=600)),
            ],
        ),
    ]
