# Generated by Django 3.2.9 on 2021-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('nombre_grupo_usuario', models.CharField(choices=[('Usuario', 'Usuario'), ('Administrador', 'Administrador')], max_length=20)),
                ('last_login', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
